theme = "edidor"
title = "TrungKFC"
baseurl = "https://vnstrawhat.github.io"
AuthorName = "TrungKFC"
# place your logo file to ./static/images to set logo

# i18n is not completed yet, help is appreciated.
languageCode = "en"
defaultContentLanguage = "en"
# you may not need this
hasCJKLanguage = true


# ----- feel free change these settings, those are not tied to this theme --
paginate = 7
enableEmoji = true

# to have better preview
buildDrafts = "false"
# helpful if you want to edit the site or theme code
disableFastRender = true
# --------------------------------------------------------------------------

disqusShortname = "your disqus short name"
googleAnalytics = "your ga id"

# social link in the footer, change it to "" hide it
[social]
    github = " "
    facebook = " "
    twitter = " "
    email = " "

# author, title, description are used in the home page, you can embed html tag in description
[params]
    # will use AuthorName if you leave it blank, but you can set it to arbitrary text
    author = "TrungKFC"
    title = "TrungKFC"
    description = ""
    # change it to false if you don't need syntax highlighting, and save a little bandwidth
    isHighlightCode = true
    # set true need to use custom js
    useCustomSyntaxHighlight = false
    customJs = []
    customCss = ["kfc.css"]
    mode = "dark"
# menubar setting, you can change url, weight and name except the 'Theme'.
[[menu.main]]
    name = "Article"
    url = "#"
    weight = 1
[[menu.main]]
    name = "View"
    url = "#"
    weight = 10
[[menu.main]]
    name = "About"
    url = "/"
    weight = 11
# You can change the name, but please don't edit the identifier
[[menu.main]]
    parent = "View"
    identifier = "toggle-sidebar"
    name = "Toggle Sidebar"
    url = "#"
    weight = 10
[[menu.main]]
    parent = "Article"
    name = "Posts"
    url = "/posts"
    weight = 1
[[menu.main]]
    parent = "Article"
    name = "Tags"
    url = "/tags"
    weight = 20
[[menu.main]]
    parent = "Article"
    name = "Categories"
    url = "/categories"
    weight = 30
